name: Docker build setup
on:
  push:
    tags:
      - 'setup-v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | sed 's/refs\/tags\/setup-v//')
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: louislau/wildduck-dockerized-setup:${{steps.get_version.outputs.VERSION}}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}